version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python json-pdf-layer.py
      - npm init --yes
      - npm install -g serverless
      - npm install --save serverless-python-requirements
      - ls /
      - serverless deploy
