version: 0.2

phases:
  install:
    commands:
      - yum -y groupinstall development
      - echo "development done."
      - yum -y install zlib-devel
      - echo "zlib-devel done."
      - wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz
      - echo "python downloading..."
      - echo "python dowloaded."
      - tar xJf Python-3.7.4.tar.xz
      - cd Python-3.7.4
      - echo "configure started..."
      - ./configure
      - echo "make started..."
      - make
      - echo "make install started"
      - make install
      - echo "get-py.py downloading..."
      - wget https://bootstrap.pypa.io/get-pip.py
      - echo "get-pip.py downloaded."
      - python3 get-pip.py
      - echo "pip start upgrade..."
      - pip install --upgrade pip
      - echo "pybars3 installing..."
      - pip install pybars3
      - echo "pyppeteer installing..."
      - pip install pyppeteer
  build:
    commands:
      - echo "Start json-pdf-app.py"
      - python json-pdf-app

