version: 0.2

phases:
  install:
    commands:
      - apt install gcc libffi-devel python-devel openssl-devel --yes
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python libs_builder.py
      - ls layers/JsonPdfEnginePath/python/lib/python3.7/site-packages
      - npm install -g serverless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - serverless deploy --aws-profile default
