version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - git clone https://github.com/ollyajoke/headless-chromium.git
      - ls
      - python browser_get.py
      - cp -r /root/.local/share/pyppeteer/local-chromium/575458/chrome-linux layers/JsonPdfEnginePath/python/lib/python3.7/site-packages
      - python libs_builder.py
      - ls layers/JsonPdfEnginePath/python/lib/python3.7/site-packages
      - npm install -g serverless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - serverless deploy --aws-profile default
