version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - ls /root/.local
      - ls /root/.local/share
      - python checkdir.py
      - python layers/json-pdf-engine.py
      - npm install -g serverless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - serverless remove && serverless deploy -v --aws-profile default
