version: 0.2

phases:
  install:
    commands:
      - ls -a /usr/local/lib/python3.7/site-packages
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - ls -a /usr/local/lib/python3.7/site-packages
      - ls -a /usr/lib
      - python libs_builder.py
      - ls -a layers/JsonPdfEnginePath/python/lib/python3.7/site-packages
      - npm install -g serverless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - serverless deploy --aws-profile default
