version: 0.2

phases:
  install:
    commands: 
      - python3 -V
      - pip3 -V
      - pip install --upgrade pip
      - pip3 -V
      - pip3 install pybars3
      - pip3 install pyppeteer
      
