version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python libs_builder.py
      - ls /usr/lib/x86_64-linux-gnu
      - cp /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.4000.14 pango-1.0
      - cp /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.4000.14 pangocairo-1.0
      - cp /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.4000.14 .
      - ls
      - ls -a layers/JsonPdfEnginePath/python/lib/python3.7/site-packages
      - npm install -g serverless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - serverless deploy --aws-profile default
