version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - export lib_path = /usr/local/lib/python3.7/site-packages
      - export layer_source_path = /layers/JsonPdfEnginePath/python/lib/python3.7/site-packages
      - cp $lib_path/app_dirs.py $layer_source_path/
      - cp -r $lib_path/pybars $layer_source_path/
      - cp -r $lib_path/pyee $layer_source_path/
      - cp -r $lib_path/pymeta $layer_source_path/
      - cp -r $lib_path/pyppeteer $layer_source_path/
      - cp -r $lib_path/tqdm $layer_source_path/
      - cp -r $lib_path/urlib3 $layer_source_path/
      - cp -r $lib_path/websockets $layer_source_path/
      - ls $layer_source_path
      - python get_dirs.py
      - ls
      - ls /usr/local/lib/python3.7/site-packages
      - npm install -g serverless
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - serverless deploy --aws-profile default
